println("Branch name: ${BRANCH_NAME}")

switch(BRANCH_NAME) {
  case "origin/test":
    aws_region="us-east-1"
    region="info"
    src_domain="wpblog.teamlab.info"
    break
  case "origin/production_deploy":
    aws_region="us-east-1"
    region="com"
    MONITOR_ID = '8888888888888'
    src_domain="wpblog.onlyoffice.com"
    break
  default:
    println("Branch: ${BRANCH_NAME} do not for deploy.")
    break
}

pipeline {
  agent { label 'ubuntu' }
  triggers {
    githubPush()
  }
  options {
    disableConcurrentBuilds()
    buildDiscarder (logRotator(numToKeepStr: '5', artifactNumToKeepStr: '5'))
  }
  stages {
    
    stage('deploy') {
      when { 
        anyOf { branch 'origin/test';
                branch 'origin/production_deploy' }
      }
      environment {
        region = "${region}"
        src_domain="${src_domain}"
      }
      steps {
        withCredentials([string(credentialsId: 'blog_revalidate_token', variable: 'revalidate_token')]) {
        sh '''
          echo "source domain ${src_domain}"
          sed -i "s^var_src_domain^${src_domain}^" lib/api.js
          sed -i "s^var_revalidate_token^${revalidate_token}^" .env.local
          cp .jenkins/build.sh .jenkins/blog_build.sh
          tar -czpf .jenkins/blog_next.tar.gz \
            --exclude ".git" \
            --exclude ".gitignore" \
            --exclude ".jenkins" \
            --exclude "README.md" .
          
          echo "Deploy from ${BRANCH_NAME} is starting."
        '''
        }
        
        sshPublisher(publishers: [sshPublisherDesc(configName: "strapi_oforms@${region}", 
          transfers: [sshTransfer(cleanRemote: false, 
            excludes: '', 
            execCommand: '''
              sudo bash /home/ubuntu/deploy/.jenkins/blog_build.sh |& tee -a > /home/ubuntu/deploy/blog_deploy.log
            ''', 
            execTimeout: 0, 
            flatten: false, 
            makeEmptyDirs: false, 
            noDefaultExcludes: false, 
            patternSeparator: '[, ]+', 
            remoteDirectory: '', 
            remoteDirectorySDF: false, 
            removePrefix: '', 
            sourceFiles: '.jenkins/blog_next.tar.gz,.jenkins/blog_build.sh')], 
          usePromotionTimestamp: false, 
          useWorkspaceInPromotion: false, 
          verbose: false)])
      }
    }    
  }
}